create table sales_data (
						    ORDERNUMBER				int,
							QUANTITYORDERED		    smallint,
							PRICEEACH				decimal,
							ORDERLINENUMBER		    smallint,
							SALES					decimal,
							ORDERDATE				timestamp,
							STATUS					varchar(10),
							QTR_ID					smallint,
							MONTH_ID				smallint,
							YEAR_ID					smallint,
							PRODUCTLINE				varchar(20),
							MSRP					smallint,
							PRODUCTCODE				varchar(10),
							CUSTOMERNAME			varchar(100),
							PHONE					varchar(20),
							ADDRESSLINE1			varchar(100),
							ADDRESSLINE2			varchar(20),
							CITY					varchar(25),
							STATE					varchar(20),
							POSTALCODE				varchar(10),
							COUNTRY					varchar(20),
							TERRITORY				varchar(5),
							CONTACTLASTNAME		    varchar(20),
							CONTACTFIRSTNAME	    varchar(20),
							DEALSIZE			    varchar(10) );